version: "3"
services:
  api:
    container_name: api
    image: docker.io/app-gingonic/latest
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - my-networks

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge